{% set version = "1.10.1" %}
{% set release = "hdf5-1.10" %}
{% set patch = "hdf5-1.10.1" %}

package:
  name: hdf5
  version: {{ version }}

source:
  fn: {{ patch }}.tar.bz2
  url: https://www.hdfgroup.org/ftp/HDF5/releases/{{ release }}/{{ patch }}/src/{{ patch }}.tar.bz2
  md5: d89893c05ee7ea8611b51bb39450d64e

build:
  number: 1

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-style (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)

