name: root
channels:
- ccpi
- local
- dgursoy
- conda-forge
- defaults
dependencies:
- boost-cpp=1.64.0=0
- ccpi-reconstruction=0.1=py27_0
- boost=1.64.0=np113py27_2
- bzip2=1.0.6=1
- cairo=1.14.6=4
- fontconfig=2.12.1=4
- freetype=2.7=1
- gettext=0.19.7=1
- glib=2.51.4=0
- icu=58.1=1
- libnetcdf=4.4.1.1=7
- libpng=1.6.28=0
- matplotlib=2.0.2=np113py27_0
- netcdf4=1.2.9=np113py27_0
- pillow=4.1.1=py27_0
- qt=5.6.2=3
- alabaster=0.7.10=py27_0
- asn1crypto=0.22.0=py27_0
- astroid=1.4.9=py27_0
- babel=2.4.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.5=py27_0
- beautifulsoup4=4.6.0=py27_0
- bleach=1.5.0=py27_0
- cffi=1.10.0=py27_0
- chardet=3.0.4=py27_0
- colorama=0.3.9=py27_0
- conda=4.3.22=py27_0
- conda-build=3.0.6=py27_0
- conda-env=2.6.0=0
- conda-verify=2.0.0=py27_0
- configparser=3.5.0=py27_0
- contextlib2=0.5.5=py27_0
- cryptography=1.8.1=py27_0
- curl=7.49.0=1
- cycler=0.10.0=py27_0
- cython=0.25.2=py27_0
- dbus=1.10.10=0
- decorator=4.0.11=py27_0
- docutils=0.13.1=py27_0
- entrypoints=0.2.2=py27_1
- enum34=1.1.6=py27_0
- expat=2.1.0=0
- filelock=2.0.7=py27_0
- funcsigs=1.0.2=py27_0
- functools32=3.2.3.2=py27_0
- futures=3.1.1=py27_0
- get_terminal_size=1.0.0=py27_0
- glob2=0.5=py27_0
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- hdf4=4.2.12=1
- html5lib=0.999=py27_0
- idna=2.5=py27_0
- imagesize=0.7.1=py27_0
- ipaddress=1.0.18=py27_0
- ipykernel=4.6.1=py27_0
- ipython=5.3.0=py27_0
- ipython_genutils=0.2.0=py27_0
- isort=4.2.14=py27_0
- jbig=2.1=0
- jedi=0.10.2=py27_2
- jinja2=2.9.6=py27_0
- jpeg=9b=0
- jsonschema=2.6.0=py27_0
- jupyter_client=5.0.1=py27_0
- jupyter_core=4.3.0=py27_0
- lazy-object-proxy=1.2.2=py27_0
- libffi=3.2.1=1
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libiconv=1.14=0
- libsodium=1.0.10=0
- libtiff=4.0.6=3
- libxcb=1.12=1
- libxml2=2.9.4=0
- markupsafe=0.23=py27_2
- mistune=0.7.4=py27_0
- mkl=2017.0.1=0
- mock=2.0.0=py27_0
- mpmath=0.19=py27_1
- nbconvert=5.2.1=py27_0
- nbformat=4.3.0=py27_0
- networkx=1.11=py27_0
- numexpr=2.6.2=np113py27_0
- numpy=1.13.0=py27_0
- numpydoc=0.6.0=py27_0
- olefile=0.44=py27_0
- openssl=1.0.2l=0
- packaging=16.8=py27_0
- pandas=0.20.2=np113py27_0
- pandocfilters=1.4.1=py27_0
- patchelf=0.9=0
- path.py=10.3.1=py27_0
- pathlib2=2.2.1=py27_0
- pbr=1.10.0=py27_0
- pcre=8.39=1
- pep8=1.7.0=py27_0
- pexpect=4.2.1=py27_0
- pickleshare=0.7.4=py27_0
- pip=9.0.1=py27_1
- pixman=0.34.0=0
- pkginfo=1.4.1=py27_0
- prompt_toolkit=1.0.14=py27_0
- psutil=5.2.2=py27_0
- ptyprocess=0.5.1=py27_0
- py=1.4.34=py27_0
- pycairo=1.10.0=py27_0
- pycosat=0.6.2=py27_0
- pycparser=2.17=py27_0
- pycrypto=2.6.1=py27_6
- pyflakes=1.5.0=py27_0
- pygments=2.2.0=py27_0
- pylint=1.6.4=py27_1
- pyopenssl=17.0.0=py27_0
- pyparsing=2.1.4=py27_0
- pyqt=5.6.0=py27_2
- pytest=3.1.2=py27_0
- python=2.7.13=0
- python-dateutil=2.6.0=py27_0
- pytz=2017.2=py27_0
- pyyaml=3.12=py27_0
- pyzmq=16.0.2=py27_0
- qtawesome=0.4.4=py27_0
- qtconsole=4.3.0=py27_0
- qtpy=1.2.1=py27_0
- readline=6.2=2
- requests=2.14.2=py27_0
- rope=0.9.4=py27_1
- ruamel_yaml=0.11.14=py27_1
- scandir=1.5=py27_0
- scikit-image=0.13.0=np113py27_0
- scikit-learn=0.18.1=np113py27_1
- scipy=0.19.0=np113py27_0
- setuptools=27.2.0=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- six=1.10.0=py27_0
- snowballstemmer=1.2.1=py27_0
- sphinx=1.6.2=py27_0
- sphinxcontrib=1.0=py27_0
- sphinxcontrib-websupport=1.0.1=py27_0
- spyder=3.1.4=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- subprocess32=3.2.7=py27_0
- sympy=1.0=py27_0
- testpath=0.3.1=py27_0
- tk=8.5.18=0
- tornado=4.5.1=py27_0
- traitlets=4.3.2=py27_0
- typing=3.6.1=py27_0
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- wrapt=1.10.10=py27_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.5=0
- zlib=1.2.8=3
- dxchange=0.1.1=py27_0
- dxfile=0.4=py27_0
- edffile=1.6=py27_0
- fftw=3.3.4=0
- pyfftw=0.9.2=py27_0
- pywavelets=0.4.0=py27_0
- spefile=1.6=py27_0
- tifffile=0.7.0=py27_0
- tomopy=1.0.1=py27_0
- pip:
  - appdirs==1.4.3
  - backports-abc==0.5
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - cached-property==1.3.0
  - fabio==0.4.0
  - fisx==1.1.2
  - ipython-genutils==0.2.0
  - ipywidgets==6.0.0
  - jupyter==1.0.0
  - jupyter-client==5.0.1
  - jupyter-console==5.1.0
  - jupyter-core==4.3.0
  - lmfit==0.9.7
  - mako==1.0.6
  - mrcfile==1.0.0
  - notebook==5.0.0
  - nvidia-ml-py==375.53
  - peakutils==1.1.0
  - phasepack==1.5
  - polytope==0.2.0
  - prompt-toolkit==1.0.14
  - pymca==5.2.1
  - pymca5==5.2.2
  - gnureadline==6.3.8
  - pyreadline==2.1
  - pytools==2017.3
  - readme-renderer==17.2
  - restview==2.7.0
  - simpleitk==1.0.0
  - sphinx-rtd-theme==0.2.4
  - terminado==0.6
  - webencodings==0.5.1
  - widgetsnbextension==2.0.0

